export const MODULES = {
  AUTH: 'AUTH',
  USER: 'USER',
  ORGANIZATION: 'ORGANIZATION',
  FARM: 'FARM',
  CROP: 'CROP',
  LIVESTOCK: 'LIVESTOCK',
  INVENTORY: 'INVENTORY',
  HR: 'HR',
  MARKETPLACE: 'MARKETPLACE',
  IOT: 'IOT',
  NOTIFICATION: 'NOTIFICATION',
  ROLE: 'ROLE',
  PERMISSION: 'PERMISSION',
  AUDIT: 'AUDIT',
  SETTINGS: 'SETTINGS',
} as const;

export type ModuleType = typeof MODULES[keyof typeof MODULES];
