import { MODULES } from './modules';

export const PERMISSIONS = {
  // ================== MODULE AUTH ==================
  AUTH: {
    ROLE_CREATE: 'AUTH_ROLE_CREATE',
    ROLE_READ: 'AUTH_ROLE_READ',
    ROLE_UPDATE: 'AUTH_ROLE_UPDATE',
    ROLE_DELETE: 'AUTH_ROLE_DELETE',
    ROLE_LIST: 'AUTH_ROLE_LIST',
    ROLE_SEARCH: 'AUTH_ROLE_SEARCH',
    LOGIN: 'AUTH_LOGIN',
    LOGOUT: 'AUTH_LOGOUT'
  },

  // ================== MODULE USER ==================
  USER: {
    USER_CREATE: 'USER_USER_CREATE',
    USER_READ: 'USER_USER_READ',
    USER_UPDATE: 'USER_USER_UPDATE',
    USER_DELETE: 'USER_USER_DELETE',
    USER_LIST: 'USER_USER_LIST',
    USER_SEARCH: 'USER_USER_SEARCH',
    USER_ACTIVATE: 'USER_USER_ACTIVATE',
    USER_DEACTIVATE: 'USER_USER_DEACTIVATE',
    USER_CHANGE_PASSWORD: 'USER_USER_CHANGE_PASSWORD',
    USER_RESET_PASSWORD: 'USER_USER_RESET_PASSWORD',
    USER_SUSPEND: 'USER_USER_SUSPEND',
    USER_LOCK: 'USER_USER_LOCK',
    USER_UNLOCK: 'USER_USER_UNLOCK'
  },


  // ================== MODULE ORGANIZATION ==================
  ORGANIZATION: {
    SUPERSTRUCTURE_CREATE: 'ORGANIZATION_SUPERSTRUCTURE_CREATE',
    SUPERSTRUCTURE_READ: 'ORGANIZATION_SUPERSTRUCTURE_READ',
    SUPERSTRUCTURE_UPDATE: 'ORGANIZATION_SUPERSTRUCTURE_UPDATE',
    SUPERSTRUCTURE_DELETE: 'ORGANIZATION_SUPERSTRUCTURE_DELETE',
    SUPERSTRUCTURE_LIST: 'ORGANIZATION_SUPERSTRUCTURE_LIST',
    SUPERSTRUCTURE_SEARCH: 'ORGANIZATION_SUPERSTRUCTURE_SEARCH',
    STRUCTURE_CREATE: 'ORGANIZATION_STRUCTURE_CREATE',
    STRUCTURE_READ: 'ORGANIZATION_STRUCTURE_READ',
    STRUCTURE_UPDATE: 'ORGANIZATION_STRUCTURE_UPDATE',
    STRUCTURE_DELETE: 'ORGANIZATION_STRUCTURE_DELETE',
    STRUCTURE_LIST: 'ORGANIZATION_STRUCTURE_LIST',
    STRUCTURE_SEARCH: 'ORGANIZATION_STRUCTURE_SEARCH',
    CATEGORY_CREATE: 'ORGANIZATION_CATEGORY_CREATE',
    CATEGORY_READ: 'ORGANIZATION_CATEGORY_READ',
    CATEGORY_UPDATE: 'ORGANIZATION_CATEGORY_UPDATE',
    CATEGORY_DELETE: 'ORGANIZATION_CATEGORY_DELETE',
    CATEGORY_LIST: 'ORGANIZATION_CATEGORY_LIST',
    CATEGORY_SEARCH: 'ORGANIZATION_CATEGORY_SEARCH',
  },

  // ================== MODULE CATALOG ==================
  CATALOG: {
    SERVICE_CREATE: 'CATALOG_SERVICE_CREATE',
    SERVICE_READ: 'CATALOG_SERVICE_READ',
    SERVICE_UPDATE: 'CATALOG_SERVICE_UPDATE',
    SERVICE_DELETE: 'CATALOG_SERVICE_DELETE',
    SERVICE_LIST: 'CATALOG_SERVICE_LIST',
    SERVICE_SEARCH: 'CATALOG_SERVICE_SEARCH',
    SERVICE_ACTIVATE: 'CATALOG_SERVICE_ACTIVATE',
    SERVICE_DEACTIVATE: 'CATALOG_SERVICE_DEACTIVATE'
  },

  // ================== MODULE CLIENT ==================
  CLIENT: {
    CREATE: 'CLIENT_CREATE',
    READ: 'CLIENT_READ',
    UPDATE: 'CLIENT_UPDATE',
    DELETE: 'CLIENT_DELETE',
    LIST: 'CLIENT_LIST',
    SEARCH: 'CLIENT_SEARCH',
    ACTIVATE: 'CLIENT_ACTIVATE',
    DEACTIVATE: 'CLIENT_DEACTIVATE'
  },

  // ================== MODULE TERMINAL ==================
  TERMINAL: {
    CREATE: 'TERMINAL_CREATE',
    READ: 'TERMINAL_READ',
    UPDATE: 'TERMINAL_UPDATE',
    DELETE: 'TERMINAL_DELETE',
    LIST: 'TERMINAL_LIST',
    SEARCH: 'TERMINAL_SEARCH',
    ACTIVATE: 'TERMINAL_ACTIVATE',
    DEACTIVATE: 'TERMINAL_DEACTIVATE',
    MAINTAIN: 'TERMINAL_MAINTAIN',
    BLOCKED: 'TERMINAL_BLOCKED',
    CHANGE_STATUS: 'TERMINAL_CHANGE_STATUS'
  },

  // ================== MODULE TRANSACTION ==================
  TRANSACTION: {
    CREATE: 'TRANSACTION_CREATE',
    READ: 'TRANSACTION_READ',
    LIST: 'TRANSACTION_LIST',
    SEARCH: 'TRANSACTION_SEARCH',
    CANCEL: 'TRANSACTION_CANCEL',
    REFUND: 'TRANSACTION_REFUND',
    VALIDATE: 'TRANSACTION_VALIDATE'
  },

  // ================== MODULE PAYMENT ==================
  PAYMENT: {
    CREATE: 'PAYMENT_CREATE',
    READ: 'PAYMENT_READ',
    LIST: 'PAYMENT_LIST',
    SEARCH: 'PAYMENT_SEARCH',
    PROCESS: 'PAYMENT_PROCESS',
    PROCESS_CARD: 'PAYMENT_CARD_PROCESS',
    PROCESS_MM: 'PAYMENT_MM_PROCESS',
    PROCESS_CASH: 'PAYMENT_CASH_PROCESS',
    PROCESS_BT: 'PAYMENT_BT_PROCESS',
    VALIDATE: 'PAYMENT_VALIDATE',
    CANCEL: 'PAYMENT_CANCEL',
    RETRY: 'PAYMENT_RETRY',
    WEBHOOK: 'PAYMENT_WEBHOOK',
    EXPORT: 'PAYMENT_EXPORT',
    REFUND: 'PAYMENT_REFUND'
  },

  // ================== MODULE AUDIT ==================
  AUDIT: {
    READ: 'AUDIT_READ',
    LIST: 'AUDIT_LIST',
    SEARCH: 'AUDIT_SEARCH',
    EXPORT: 'AUDIT_EXPORT',
    SECURITY: 'AUDIT_SECURITY',
    STATS: 'AUDIT_STATS'
  },

  // ================== MODULE REPORT ==================
  REPORT: {
    VIEW: 'REPORT_VIEW',
    GENERATE: 'REPORT_GENERATE',
    EXPORT: 'REPORT_EXPORT',
    SCHEDULE: 'REPORT_SCHEDULE'
  },

  // ================== MODULE SETTINGS ==================
  SETTINGS: {
    READ: 'SETTINGS_READ',
    UPDATE: 'SETTINGS_UPDATE',
    CONFIGURE: 'SETTINGS_CONFIGURE'
  },

  // ================== PERMISSIONS SPÉCIALES ==================
  SPECIAL: {
    VIEW_SYSTEM_ROLES: 'VIEW_SYSTEM_ROLES',
    MANAGE_ROLES: 'MANAGE_ROLES',
    VIEW_STATISTICS: 'VIEW_STATISTICS',
    CLIENT_BLOCK: 'CLIENT_BLOCK',
    CLIENT_STATS: 'CLIENT_STATS',
    TRANSACTION_UPDATE_STATUS: 'TRANSACTION_UPDATE_STATUS',
    TRANSACTION_STATS: 'TRANSACTION_STATS',
    TRANSACTION_EXPORT: 'TRANSACTION_EXPORT',
    STOCK_MANAGE: 'STOCK_MANAGE',
    STOCK_READ: 'STOCK_READ'
  },

  // ================== RECEIPT PERMISSIONS ==================
  RECEIPT: {
    CREATE: 'RECEIPT_CREATE',
    READ: 'RECEIPT_READ',
    UPDATE: 'RECEIPT_UPDATE',
    SEND: 'RECEIPT_SEND',
    STATS: 'RECEIPT_STATS'
  },

  // ================== WEBHOOK PERMISSIONS ==================
  WEBHOOK: {
    READ: 'WEBHOOK_READ',
    UPDATE: 'WEBHOOK_UPDATE',
    RETRY: 'WEBHOOK_RETRY',
    STATS: 'WEBHOOK_STATS',
    TEST: 'WEBHOOK_TEST'
  },

  // ================== SERVICE CONFIG PERMISSIONS ==================
  SERVICE_CONFIG: {
    CREATE: 'SERVICE_CONFIG_CREATE',
    READ: 'SERVICE_CONFIG_READ',
    UPDATE: 'SERVICE_CONFIG_UPDATE'
  }
} as const;

// Types pour la validation TypeScript
export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS][keyof typeof PERMISSIONS[keyof typeof PERMISSIONS]];

// Utilitaires pour vérifier les permissions
export const hasPermission = (userPermissions: string[], requiredPermission: PermissionKey): boolean => {
  return userPermissions.includes(requiredPermission);
};

export const hasAnyPermission = (userPermissions: string[], requiredPermissions: PermissionKey[]): boolean => {
  return requiredPermissions.some(permission => userPermissions.includes(permission));
};

export const hasAllPermissions = (userPermissions: string[], requiredPermissions: PermissionKey[]): boolean => {
  return requiredPermissions.every(permission => userPermissions.includes(permission));
};

// Groupement par module pour faciliter l'utilisation
export const PERMISSIONS_BY_MODULE = {
  [MODULES.AUTH]: PERMISSIONS.AUTH,
  [MODULES.USER]: PERMISSIONS.USER,
  [MODULES.ORGANIZATION]: PERMISSIONS.ORGANIZATION,
  [MODULES.CATALOG]: PERMISSIONS.CATALOG,
  [MODULES.CLIENT]: PERMISSIONS.CLIENT,
  [MODULES.TERMINAL]: PERMISSIONS.TERMINAL,
  [MODULES.TRANSACTION]: PERMISSIONS.TRANSACTION,
  [MODULES.PAYMENT]: PERMISSIONS.PAYMENT,
  [MODULES.AUDIT]: PERMISSIONS.AUDIT,
  [MODULES.REPORT]: PERMISSIONS.REPORT,
  [MODULES.SETTINGS]: PERMISSIONS.SETTINGS
} as const;