import { MODULES } from './modules';

export const PERMISSIONS = {
  // ================== AUTH ==================
  AUTH: {
    LOGIN: 'AUTH.AUTH.LOGIN',
    LOGOUT: 'AUTH.AUTH.LOGOUT',
  },

  // ================== USERS ==================
  USER: {
    CREATE: 'USERS.USER.CREATE',
    VIEW: 'USERS.USER.VIEW',
    EDIT: 'USERS.USER.EDIT',
    DELETE: 'USERS.USER.DELETE',
    LIST: 'USERS.USER.LIST',
    SEARCH: 'USERS.USER.SEARCH',
    CHANGE_STATUS: 'USERS.USER.CHANGE_STATUS',
    VIEW_STATS: 'USERS.USER.VIEW_STATS',
  },

  // ================== ROLES ==================
  ROLE: {
    CREATE: 'ROLES.ROLE.CREATE',
    VIEW: 'ROLES.ROLE.VIEW',
    EDIT: 'ROLES.ROLE.EDIT',
    DELETE: 'ROLES.ROLE.DELETE',
    LIST: 'ROLES.ROLE.LIST',
    SEARCH: 'ROLES.ROLE.SEARCH',
    MANAGE: 'ROLES.ROLE.MANAGE',
  },

  // ================== PERMISSIONS ==================
  PERMISSION: {
    VIEW: 'PERMISSIONS.PERMISSION.VIEW',
    LIST: 'PERMISSIONS.PERMISSION.LIST',
    LIST_BY_MODULE: 'PERMISSIONS.PERMISSION.LIST_BY_MODULE',
    SEARCH: 'PERMISSIONS.PERMISSION.SEARCH',
  },

  // ================== ORGANIZATIONS ==================
  ORGANIZATION: {
    CREATE: 'ORGANIZATIONS.ORGANIZATION.CREATE',
    VIEW: 'ORGANIZATIONS.ORGANIZATION.VIEW',
    EDIT: 'ORGANIZATIONS.ORGANIZATION.EDIT',
    DELETE: 'ORGANIZATIONS.ORGANIZATION.DELETE',
    LIST: 'ORGANIZATIONS.ORGANIZATION.LIST',
    SEARCH: 'ORGANIZATIONS.ORGANIZATION.SEARCH',
    CHANGE_STATUS: 'ORGANIZATIONS.ORGANIZATION.CHANGE_STATUS',
    VIEW_STATS: 'ORGANIZATIONS.ORGANIZATION.VIEW_STATS',
  },

  // ================== FARMS ==================
  FARM: {
    CREATE: 'FARMS.FARM.CREATE',
    VIEW: 'FARMS.FARM.VIEW',
    EDIT: 'FARMS.FARM.EDIT',
    DELETE: 'FARMS.FARM.DELETE',
    LIST: 'FARMS.FARM.LIST',
    SEARCH: 'FARMS.FARM.SEARCH',
    CHANGE_STATUS: 'FARMS.FARM.CHANGE_STATUS',
    VIEW_STATS: 'FARMS.FARM.VIEW_STATS',
  },

  // ================== CROPS ==================
  CROP: {
    CREATE: 'CROPS.CROP.CREATE',
    VIEW: 'CROPS.CROP.VIEW',
    EDIT: 'CROPS.CROP.EDIT',
    DELETE: 'CROPS.CROP.DELETE',
    LIST: 'CROPS.CROP.LIST',
    SEARCH: 'CROPS.CROP.SEARCH',
    PARCEL_VIEW: 'CROPS.CROP.VIEW',
    CULTIVATION_VIEW: 'CROPS.CROP.VIEW',
  },

  // ================== LIVESTOCK ==================
  LIVESTOCK: {
    CREATE: 'LIVESTOCK.ANIMAL.CREATE',
    VIEW: 'LIVESTOCK.ANIMAL.VIEW',
    EDIT: 'LIVESTOCK.ANIMAL.EDIT',
    DELETE: 'LIVESTOCK.ANIMAL.DELETE',
    LIST: 'LIVESTOCK.ANIMAL.LIST',
  },

  // ================== INVENTORY ==================
  INVENTORY: {
    ITEM_VIEW: 'INVENTORY.ITEM.VIEW',
    ITEM_LIST: 'INVENTORY.ITEM.LIST',
    ITEM_MANAGE: 'INVENTORY.ITEM.MANAGE',
    ITEM_CREATE: 'INVENTORY.ITEM.MANAGE',
    ITEM_UPDATE: 'INVENTORY.ITEM.MANAGE',
    ITEM_DELETE: 'INVENTORY.ITEM.MANAGE',
    MOVEMENT_CREATE: 'INVENTORY.ITEM.MANAGE',
    MOVEMENT_VIEW: 'INVENTORY.ITEM.VIEW',
    MOVEMENT_DELETE: 'INVENTORY.ITEM.MANAGE',
  },

  // ================== HR ==================
  HR: {
    EMPLOYEE_VIEW: 'HR.EMPLOYEE.VIEW',
    EMPLOYEE_LIST: 'HR.EMPLOYEE.LIST',
    EMPLOYEE_MANAGE: 'HR.EMPLOYEE.MANAGE',
    EMPLOYEE_CREATE: 'HR.EMPLOYEE.MANAGE',
    EMPLOYEE_UPDATE: 'HR.EMPLOYEE.MANAGE',
    EMPLOYEE_DELETE: 'HR.EMPLOYEE.MANAGE',
    TASK_VIEW: 'HR.EMPLOYEE.VIEW',
    TASK_CREATE: 'HR.EMPLOYEE.MANAGE',
    ATTENDANCE_VIEW: 'HR.EMPLOYEE.VIEW',
    ATTENDANCE_CREATE: 'HR.EMPLOYEE.MANAGE',
  },

  // ================== MARKETPLACE ==================
  MARKETPLACE: {
    PRODUCT_VIEW: 'MARKETPLACE.PRODUCT.VIEW',
    PRODUCT_LIST: 'MARKETPLACE.PRODUCT.LIST',
    PRODUCT_MANAGE: 'MARKETPLACE.PRODUCT.MANAGE',
    PRODUCT_CREATE: 'MARKETPLACE.PRODUCT.MANAGE',
    CUSTOMER_VIEW: 'MARKETPLACE.PRODUCT.VIEW',
    CUSTOMER_CREATE: 'MARKETPLACE.PRODUCT.MANAGE',
    ORDER_VIEW: 'MARKETPLACE.PRODUCT.VIEW',
    ORDER_CREATE: 'MARKETPLACE.PRODUCT.MANAGE',
    ORDER_EDIT: 'MARKETPLACE.PRODUCT.MANAGE',
    ORDER_DELETE: 'MARKETPLACE.PRODUCT.MANAGE',
  },

  // ================== IOT ==================
  IOT: {
    SENSOR_CREATE: 'IOT.SENSOR.CREATE',
    SENSOR_VIEW: 'IOT.SENSOR.VIEW',
    SENSOR_EDIT: 'IOT.SENSOR.EDIT',
    SENSOR_LIST: 'IOT.SENSOR.LIST',
    READING_CREATE: 'IOT.READING.CREATE',
    READING_VIEW: 'IOT.READING.VIEW',
  },

  // ================== NOTIFICATIONS ==================
  NOTIFICATION: {
    VIEW: 'NOTIFICATIONS.NOTIFICATION.VIEW',
    CREATE: 'NOTIFICATIONS.NOTIFICATION.CREATE',
  },

  // ================== REPORTS ==================
  REPORT: {
    VIEW: 'REPORTS.REPORT.VIEW',
    EXPORT: 'REPORTS.REPORT.EXPORT',
  },

  // ================== FINANCE ==================
  FINANCE: {
    VIEW: 'FINANCE.TRANSACTION.VIEW',
    LIST: 'FINANCE.TRANSACTION.LIST',
    MANAGE: 'FINANCE.TRANSACTION.MANAGE',
    APPROVE: 'FINANCE.TRANSACTION.APPROVE',
  },

  // ================== AUDIT ==================
  AUDIT: {
    VIEW: 'AUDIT.LOG.VIEW',
    LIST: 'AUDIT.LOG.LIST',
  },

  // ================== SETTINGS ==================
  SETTINGS: {
    READ: 'SETTINGS.SETTING.READ',
    UPDATE: 'SETTINGS.SETTING.UPDATE',
    CONFIGURE: 'SETTINGS.SETTING.CONFIGURE',
  },
} as const;

// Types
export type PermissionKey = string;

// Utilities
export const hasPermission = (userPermissions: string[], requiredPermission: string): boolean => {
  return userPermissions.includes(requiredPermission);
};

export const hasAnyPermission = (userPermissions: string[], requiredPermissions: string[]): boolean => {
  return requiredPermissions.some(permission => userPermissions.includes(permission));
};

export const hasAllPermissions = (userPermissions: string[], requiredPermissions: string[]): boolean => {
  return requiredPermissions.every(permission => userPermissions.includes(permission));
};

// Groupement par module
export const PERMISSIONS_BY_MODULE = {
  [MODULES.AUTH]: PERMISSIONS.AUTH,
  [MODULES.USER]: PERMISSIONS.USER,
  [MODULES.ROLE]: PERMISSIONS.ROLE,
  [MODULES.PERMISSION]: PERMISSIONS.PERMISSION,
  [MODULES.ORGANIZATION]: PERMISSIONS.ORGANIZATION,
  [MODULES.FARM]: PERMISSIONS.FARM,
  [MODULES.CROP]: PERMISSIONS.CROP,
  [MODULES.LIVESTOCK]: PERMISSIONS.LIVESTOCK,
  [MODULES.INVENTORY]: PERMISSIONS.INVENTORY,
  [MODULES.HR]: PERMISSIONS.HR,
  [MODULES.MARKETPLACE]: PERMISSIONS.MARKETPLACE,
  [MODULES.IOT]: PERMISSIONS.IOT,
  [MODULES.NOTIFICATION]: PERMISSIONS.NOTIFICATION,
  [MODULES.AUDIT]: PERMISSIONS.AUDIT,
  [MODULES.SETTINGS]: PERMISSIONS.SETTINGS,
} as const;
